version: "2"
services: 
  web:
    environment: 
      - MONGO_CONNECTION_URL=mongodb://mongo:27017
    build: .
    ports: 
      - "3000:3000"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
  